Remove "" from links

diff --git a/system/bin/rmlwk b/system/bin/rmlwk
--- a/system/bin/rmlwk
+++ b/system/bin/rmlwk
@@ -98,7 +98,7 @@ case "$(tolower "$1")" in
         block_type=${1#--block-}
         echo "- Downloading entries for ${block_type}."
         sleep 0.5
-        wget -O /data/local/tmp/hosts "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/${block_type}-only/hosts" || abort "Failed to download hosts file."
+        wget -O /data/local/tmp/hosts https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/${block_type}-only/hosts || abort "Failed to download hosts file."
         echo "- Applying enteries..."
         cat /data/local/tmp/hosts "$hosts_file" | sort | uniq > "$hosts_file"
         echo "- Entries for blocking ${block_type} sites are added successfully."
@@ -116,7 +116,7 @@ case "$(tolower "$1")" in
     --update-hosts)
         echo "- Downloading update.."
         sleep 0.5
-        wget -O /data/local/tmp/hosts "https://hosts.ubuntu101.co.za/hosts" || abort "Failed to download hosts file."
+        wget -O /data/local/tmp/hosts https://hosts.ubuntu101.co.za/hosts || abort "Failed to download hosts file."
         echo "- Applying update."
         cat /data/local/tmp/hosts "$hosts_file" | sort | uniq > "$hosts_file"
         echo "- Done."
