`Enhanced ads, malware and trackers blocking experience and improved installation script, and created service.sh`

diff --git a/system/bin/rmlwk b/system/bin/rmlwk
--- a/system/bin/rmlwk
+++ b/system/bin/rmlwk
@@ -133,8 +133,11 @@ case "$(tolower "$1")" in
         wget --no-check-certificate -O /data/local/tmp/hosts1 https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts &>/dev/null || abort "Failed to download hosts file." #122k hosts
         wget --no-check-certificate -O /data/local/tmp/hosts2 https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/pro.plus-compressed.txt &>/dev/null || abort "Failed to download hosts file." 
         wget --no-check-certificate -O /data/local/tmp/hosts3 https://hblock.molinero.dev/hosts &>/dev/null || abort "Failed to download hosts file." # 458k hosts 
+        wget --no-check-certificate -O /data/local/tmp/hosts4 https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt &>/dev/null || abort "Failed to download hosts file."
+        wget --no-check-certificate -O /data/local/tmp/hosts5 https://raw.githubusercontent.com/r-a-y/mobile-hosts/refs/heads/master/AdguardMobileAds.txt &>/dev/null || abort "Failed to download hosts file."
+        wget --no-check-certificate -O /data/local/tmp/hosts6 https://raw.githubusercontent.com/r-a-y/mobile-hosts/refs/heads/master/AdguardMobileSpyware.txt &>/dev/null || abort "Failed to download hosts file."
         echo "- Applying update."
-        cat /data/local/tmp/hosts1 /data/local/tmp/hosts2 /data/local/tmp/hosts3 "$hosts_file" | sort | uniq > "$hosts_file"
+        cat /data/local/tmp/hosts1 /data/local/tmp/hosts2 /data/local/tmp/hosts3 /data/local/tmp/hosts4 /data/local/tmp/hosts5 /data/local/tmp/hosts6 "$hosts_file" | sort | uniq > "$hosts_file"
         string="description=Status: Protection is enabled ✅ | protection update date: $(date)"
         sed -i "s/^description=.*/$string/g" $MODDIR/module.prop
         echo "- Done."
